# Generated by Django 5.2.17 on 2026-10-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('custom_order', 'Demande sur mesure'), ('customer_review', 'Avis client'), ('other', 'Autre')], max_length=32)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'message de contact',
                'verbose_name_plural': 'messages de contact',
                'ordering': ['-created_at'],
            },
        ),
    ]
