# Generated by Django 5.2.17 on 2026-10-06 12:05

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=80)),
                ('position', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'catégorie',
                'verbose_name_plural': 'catégories',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'couleur',
                'verbose_name_plural': 'couleurs',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('label', models.CharField(max_length=8)),
                ('position', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'taille',
                'verbose_name_plural': 'tailles',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='nom')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='prix de base')),
                ('offers_knot', models.BooleanField(default=False, verbose_name='avec nœud')),
                ('knot_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='supplément nœud')),
                ('is_active', models.BooleanField(default=True, verbose_name='visible')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.category', verbose_name='catégorie')),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.color', verbose_name='couleur')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.size', verbose_name='taille')),
            ],
            options={
                'verbose_name': 'variante',
                'verbose_name_plural': 'variantes',
                'constraints': [models.UniqueConstraint(condition=models.Q(('color__isnull', False)), fields=('product', 'size', 'color'), name='uniq_variant_product_size_color'), models.UniqueConstraint(condition=models.Q(('color__isnull', True)), fields=('product', 'size'), name='uniq_variant_product_size_without_color')],
            },
        ),
    ]
